#!/usr/bin/env bash

# Based on Platform:
if [[ `uname` == 'Linux' ]]; then

    # Get and build OpenBlas (Torch is much better with a decent Blas)
    cd /tmp/
    git clone https://github.com/xianyi/OpenBLAS.git
    cd OpenBLAS
    make NO_AFFINITY=1 USE_OPENMP=1
    RET=$?; if [ $RET -ne 0 ]; then
	echo "Error. OpenBLAS could not be compiled";
	exit $RET;
    fi
    sudo make install
    RET=$?; if [ $RET -ne 0 ]; then
	echo "Error. OpenBLAS could not be compiled";
	exit $RET;
    fi

else
    # Unsupported
    echo '==> platform not supported, aborting'
    exit
fi
