function [detections] = ParseDetectionsFile(filePath)
% parsing detections file, generated by AlignDataset.m
% file format - [image_path],[aligned_image_path],[detection 4D vector]

detections = containers.Map; 
fid = fopen(filePath);
C = textscan(fid, '%s %s %s', 'Delimiter', ',');
imagePaths = C{1};
alignedImagePaths = C{2};
detectionsVecs = C{3};
nImages = length(imagePaths);

for iDetection = 1:nImages
    % cut aligned image path and save only [figure_name]/[image_name]
    alignedImagePath = alignedImagePaths{iDetection};
    [temp, alignedImageName ext] = fileparts(alignedImagePath);
    [temp, figureName] = fileparts(temp);
    key = fullfile(figureName, [alignedImageName ext]);
    
    % parse detections string
    detectionVec = sscanf(detectionsVecs{iDetection}, '%f %f %f %f');
    
    if isKey(detections, key)
        disp(key);
    end
    detections(key) = struct('path', imagePaths{iDetection}, 'detection', detectionVec);
end

fclose(fid);

end
