function show_points(d,threedee_landmarks,scale)
    plot3(d(:,1)/scale,... 
          d(:,2)/scale,... 
          d(:,3)/scale,...
          'g.'); 
    hold on; 
    plot3(threedee_landmarks(:,1),...
          threedee_landmarks(:,2),...
          threedee_landmarks(:,3),...
          'r.')